spring:
  application:
    name: ECounselling

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/railway
    username: root
    password: ${MYSQL_PASSWORD:EQshhdICaeuWezLkJYdeQunEMHqJEFKi}
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    allow-circular-references: true

