spring:
  application:
    name: ECounselling

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/railway
    username: root
    password: DkXiFcvEypBpnpITQfnIoiDqvOEJqWIk
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: lucifer2447415@gmail.com
    password: zfsj iwtj gcuh hxpn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
