spring:
  application:
    name: ECounselling

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/aec
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: lucifer2447415@gmail.com
    password: ${MAIL_PASSWORD:zfsj iwtj gcuh hxpn}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  profiles:
    active: ${ENV:dev}

jwt:
  secret-key: ${SECRET_KEY:TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V}

server:
  port: 8085